force-app/main/default/objects/Sell_Item__c/Sell_Item__c.object-meta.xml
<CustomObject>
    <label>Sell Item</label>
    <nameField>
        <label>Sell Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sell_Item__c/fields/Initial_Cost__c.field-meta.xml
<CustomField>
    <fullName>Initial_Cost__c</fullName>
    <label>Initial Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sell_Item__c/fields/Parameter_A__c.field-meta.xml
<CustomField>
    <fullName>Parameter_A__c</fullName>
    <label>Parameter A</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sell_Item__c/fields/Parameter_B__c.field-meta.xml
<CustomField>
    <fullName>Parameter_B__c</fullName>
    <label>Parameter B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AdvancedPriceCalculator.cls
public with sharing class AdvancedPriceCalculator implements IPriceCalculatorService {
    public Decimal calculatePrice(final Sell_Item__c sellItem) {
        Set<String> fieldsToCheck = new Set<String> {'Parameter_A__c', 'Parameter_B__c', 'Initial_Cost__c'};

        for (String sellItemField : fieldsToCheck) {
            if (null == sellItem.get(sellItemField)) {
                throw new PriceCalculationServiceException(
                    String.format(
                        '{0} cannot be blank during Advanced Price Calculation!',
                        new String [] { sellItemField }
                    )
                );
            }
        }

        return sellItem.Initial_Cost__c + 0.25 * sellItem.Parameter_A__c + (sellItem.Parameter_A__c * sellItem.Parameter_B__c);
    }
}