force-app/main/default/objects/Sell_Item__c/Sell_Item__c.object-meta.xml
<CustomObject>
    <label>Sell Item</label>
    <nameField>
        <label>Sell Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sell_Item__c/fields/Price_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_Type__c</fullName>
    <label>Price Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Price</fullName>
            </value>
            <value>
                <fullName>Advanced Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SellItemService.cls
public with sharing class SellItemService {

    public void calculatePricesForGivenItems(final List<Sell_Item__c> sellItems) {
        PriceCalculatorInjector pcInjector = new PriceCalculatorInjector();
        IPriceCalculatorService pcService;

        for (Sell_Item__c sellItem : sellItems) {
            pcService = pcInjector.getCalculatorService(sellItem);
            if (null == pcService) {
                sellItem.addError(
                        String.format(
                            'Was not possible to find price calculator for {0} price type!',
                            new String[] { sellItem.Price_Type__c }
                        )
                );
            } else {
                sellItem.Price__c = pcService.calculatePrice(sellItem);
            }
        }
    }

    public class SellItemServiceException extends Exception {}
}