force-app/main/default/objects/NotificationMessage__mdt/NotificationMessage__mdt.object-meta.xml
<CustomObject>
    <label>Notification Message</label>
    <pluralLabel>Notification Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/NotificationMessage__mdt/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/FromDate__c.field-meta.xml
<CustomField>
    <fullName>FromDate__c</fullName>
    <label>From Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/HelpURL__c.field-meta.xml
<CustomField>
    <fullName>HelpURL__c</fullName>
    <label>Help URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/IsLink__c.field-meta.xml
<CustomField>
    <fullName>IsLink__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NotificationMessage__mdt/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationMessageContent__mdt/NotificationMessageContent__mdt.object-meta.xml
<CustomObject>
    <label>Notification Message Content</label>
    <pluralLabel>Notification Message Contents</pluralLabel>
</CustomObject>

force-app/main/default/objects/NotificationMessageContent__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationMessageContent__mdt/fields/NotificationMessage__c.field-meta.xml
<CustomField>
    <fullName>NotificationMessage__c</fullName>
    <label>Notification Message</label>
    <referenceTo>NotificationMessage__mdt</referenceTo>
    <relationshipLabel>Notification Message Contents</relationshipLabel>
    <relationshipName>NotificationMessageContents</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NotificationMessageContent__mdt/fields/TextContent__c.field-meta.xml
<CustomField>
    <fullName>TextContent__c</fullName>
    <label>Text Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationMessageContent__mdt/fields/TextType__c.field-meta.xml
<CustomField>
    <fullName>TextType__c</fullName>
    <label>Text Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificationMessageSelector.cls
public with sharing class NotificationMessageSelector {

    public static NotificationMessageSelector selector = new NotificationMessageSelector();

    public List<NotificationMessage__mdt> getMessagesByPageName(final Set<String> pageNames, Datetime timeNow) {
        return [SELECT Id, EndDate__c, FromDate__c, HelpURL__c, IsLink__c,
                        Order__c, Variant__c,
                (SELECT Id, NotificationMessage__c, Order__c, TextContent__c, TextType__c
                FROM NotificationMessageContents__r
                WHERE IsActive__c = true)
                FROM NotificationMessage__mdt
                WHERE Group__c IN :pageNames
                AND FromDate__c <= :timeNow AND EndDate__c >= :timeNow
                ORDER BY Order__c ASC NULLS LAST
        ];
    }
}